export const ProgrammingLanguagePair: { id: string, name: string }[] = [
  { id: "unknown", name: "N/A" },
  { id: "c", name: "C" },
  { id: "cpp", name: "C++" },
  { id: "java", name: "Java" },
  { id: "python", name: "Python" },
  { id: "csharp", name: "C#" },
  { id: "php", name: "PHP" },
  { id: "javascript", name: "JavaScript" },
  { id: "ruby", name: "Ruby" },
  { id: "swift", name: "Swift" },
  { id: "rust", name: "Rust" },
  { id: "typescript", name: "TypeScript" },
  { id: "kotlin", name: "Kotlin" },
  { id: "go", name: "Go" },
  { id: "scala", name: "Scala" },
  { id: "r", name: "R" },
  { id: "perl", name: "Perl" },
  { id: "haskell", name: "Haskell" },
  { id: "lua", name: "Lua" },
  { id: "d", name: "D" },
  { id: "fsharp", name: "F#" },
  { id: "clojure", name: "Clojure" },
  { id: "groovy", name: "Groovy" },
  { id: "objective-c", name: "Objective-C" },
  { id: "pascal", name: "Pascal" },
  { id: "ocaml", name: "OCaml" },
  { id: "coffeescript", name: "CoffeeScript" },
  { id: "bash", name: "Bash" },
  { id: "fortran", name: "Fortran" },
];

export default ProgrammingLanguagePair;
