[package]
name = "phijudge-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.9.2", features = ["tls"] }
tonic-build = "0.9.2"
protobuf = "3.2.0"
prost = "0.11.9"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.3.3", features = ["derive"] }

[build-dependencies]
tonic-build = "0.9.2"
