[package]
name = "phijudge-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.9.2"
tonic-build = "0.9.2"
protobuf = "3.2.0"
prost = "0.11.9"

[build-dependencies]
tonic-build = "0.9.2"
